# Generated by Django 3.0.6 on 2020-06-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeList', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='afrosamurai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Afro Samurai',
            },
        ),
        migrations.CreateModel(
            name='animelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Anime List',
            },
        ),
        migrations.CreateModel(
            name='aot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Attack On Titans',
            },
        ),
        migrations.CreateModel(
            name='bleach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Bleach',
            },
        ),
        migrations.CreateModel(
            name='bnha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'My Hero Accadamy',
            },
        ),
        migrations.CreateModel(
            name='deathnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Death Note',
            },
        ),
        migrations.CreateModel(
            name='fairytail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Fairy Tail',
            },
        ),
        migrations.CreateModel(
            name='fmab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Full Metal Alchemist Brotherhood',
            },
        ),
        migrations.CreateModel(
            name='haikyu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Haikyu',
            },
        ),
        migrations.CreateModel(
            name='hxh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Hunter X Hunter',
            },
        ),
        migrations.CreateModel(
            name='kny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Demon Slayer',
            },
        ),
        migrations.CreateModel(
            name='naruto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Naruto',
            },
        ),
        migrations.CreateModel(
            name='onepunchman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'One Punch Man',
            },
        ),
        migrations.AlterModelOptions(
            name='onepiece',
            options={'verbose_name_plural': 'One Piece'},
        ),
    ]
