# Generated by Django 3.0.6 on 2020-06-10 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeList', '0002_auto_20200610_1429'),
    ]

    operations = [
        migrations.DeleteModel(
            name='animelist',
        ),
    ]
