# Generated by Django 3.0.6 on 2020-06-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnimeList', '0003_delete_animelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='boruto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Boruto',
            },
        ),
        migrations.CreateModel(
            name='tokyoghoul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Episode', models.PositiveIntegerField()),
                ('EpisodeLink', models.URLField()),
                ('Discription', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
            options={
                'verbose_name_plural': 'Tokyo Ghoul',
            },
        ),
    ]
