# Generated by Django 3.0.6 on 2020-06-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animelist',
            name='url',
        ),
        migrations.AlterField(
            model_name='topanime',
            name='url',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
