# Generated by Django 3.0.6 on 2020-06-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200611_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='animelist',
            name='url',
            field=models.CharField(default=models.CharField(max_length=50), max_length=50),
        ),
    ]
